### ISSUE TITLE
Run failed

### ISSUE THREAD

**Issue by ShafeequeIGSNRR** [WilcoTerink/SPHY_interface#1]
I built SPHY model in Hunza catchment (a sub-catchment in Upper Indus Basin) using  Hindu_Kush_Himalaya database. I followed the instruction provided in tutorial and GUI manual. The model run was unsuccessful. I tried to figure out but couldn't get what's the reason. I attached the screenshots of model setup based on GUI. Please help me to find the cause of failure. Thanks
[SPHYrunfailed.pdf](https://github.com/WilcoTerink/SPHY_interface/files/3803102/SPHYrunfailed.pdf)

**Comment by WilcoTerink** [comment]
Hi,

I noticed you are using SPHY 2.1? The interface only works with the 2.0.* versions. I suggest you follow the instructions here to install SPHY:

https://sphy.readthedocs.io/en/latest/releases.html#release-2-0-4

Furthermore it is important that you use the same bit version of:
pcraster 
Python
Qgis 

So they all have to be 32 bits of 64 bits.

I think if you follow these steps it will work.

**Comment by WilcoTerink** [comment]
Sphy version 2.0.3 would be the best choice from the link in my previous message.

**Comment by ShafeequeIGSNRR** [comment]
Thank you very much. It started working when I replaced executable files of release SPHY 2.1 with SPHY 2.0.3.
Thanks again!
Shafeeque
![SPHY_working](https://user-images.githubusercontent.com/57341025/68181548-c08a1280-ffd2-11e9-9937-a2edc8ca787a.PNG)
