### ISSUE TITLE
Output shows values like 9.999999E+30

### ISSUE THREAD

**Issue by ShafeequeIGSNRR** [WilcoTerink/SPHY_interface#2]
I'm using SPHY pre-processor  and interface to run the model in Hunza Catchment forced by the dataset provided named as "Hindu_Kush_Himalaya". The SPHY model run successfully. But, the routed rain runoff, baseflow runoff, and total runoff are 9.9999E+30 for all the dates. While the glacier runoff and snow runoff are in normal ranges. Please help me to figure out what did I do wrong while setting up the model? 
[QTOTSubBasinTSS.xlsx](https://github.com/WilcoTerink/SPHY_interface/files/4006941/QTOTSubBasinTSS.xlsx)

**Comment by WilcoTerink** [comment]
It is likely that your land use map is missing an associated kc for one or more entries? I.e. you need to make sure that the land use map does not have holes in it and that all the land use classes have a kc in the kc.tbl.

Does that help?

**Comment by ShafeequeIGSNRR** [comment]
Thank you very much for quick response. Your recommendations worked. The SPHY model is producing results with plausible values.
