### ISSUE TITLE
Soil interpolation 

### ISSUE THREAD

**Issue by ghost** [WilcoTerink/SPHY_interface#3]
HI Wilco，

I noticed that the soil interpolation uses the bilinear method. Why did you choose this method? Thanks :)

Best,
John

**Comment by WilcoTerink** [comment]
Hi John,

I do not believe that there is any interpolation happening in the SPHY interface plugin...... If so, can you tell me what line of code?

Cheers
Wilco

**Comment by ghost** [comment]
Sorry, I mean in the pre_processor. In "spatial_processing.py"

Wilco Terink ***@***.***> 于2024年3月26日周二 22:42写道：

**Comment by WilcoTerink** [comment]
Bilinear interpolation is chosen because it is safe and robust. It doesn't lead to values outside the range of input values, something that can happen when bicubic interpolation is chosen for example.
